### ISSUE TITLE
Donation Map

### ISSUE THREAD

**Issue by hhill24** [hhill24/GreenLarder#3]
can somebody have a look at my code? I am trying to make a new map called donationMap in the scripts.js to show only the donation sites on my DonationSites.html page but the map is not appearing. The branch i'm using is called hope-branch

**Comment by DanielJakubek** [comment]
Fixed it!

First of all, add this bit of code to the css: 

#donationMap {
   position: absolute;
   top: 0;
   bottom: 0;
   width: 100%;
}

and if that does not work just get your map javascript and place it in a new js file and then link up that js and html.

This is probably not the best way to fix it but it works
